// <auto-generated />
namespace Login1CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Model_User_y_Rol : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Model_User_y_Rol));
        
        string IMigrationMetadata.Id
        {
            get { return "201909032245514_Model_User_y_Rol"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
